# Generated by Django 4.0.2 on 2022-02-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0010_ubezpieczenie_kategoria_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Samochód'), (0, 'Inne'), (4, 'Elektronika'), (2, 'Dom'), (3, 'Zdrowotne')], default=0),
        ),
    ]
