# Generated by Django 4.0.2 on 2022-02-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0011_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Zdrowotne'), (0, 'Inne'), (4, 'Elektronika'), (1, 'Samochód'), (2, 'Dom')], default=0),
        ),
    ]
