# Generated by Django 3.2.9 on 2022-02-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0011_auto_20220211_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (4, 'Elektronika'), (2, 'Dom'), (1, 'Samochód'), (3, 'Zdrowotne')], default=0),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='plakat',
            field=models.ImageField(blank=True, upload_to='plakaty'),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='tytul',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
