# Generated by Django 4.0.2 on 2022-02-11 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0012_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Dom'), (1, 'Samochód'), (0, 'Inne'), (3, 'Zdrowotne'), (4, 'Elektronika')], default=0),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='plakat',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='plakaty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='tytul',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('dodadkowy_opis', models.TextField(default='')),
                ('dane_kontaktowe', models.TextField(default='')),
                ('ubezpieczenie', models.ManyToManyField(related_name='Zamowienia', to='ubezpieczenia.Ubezpieczenie')),
            ],
        ),
    ]
