# Generated by Django 3.2.9 on 2022-02-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0012_auto_20220211_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Dom'), (1, 'Samochód'), (3, 'Zdrowotne'), (4, 'Elektronika'), (0, 'Inne')], default=0),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='plakat',
            field=models.ImageField(upload_to='plakaty'),
        ),
    ]
