# Generated by Django 4.0.2 on 2022-02-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0013_alter_dodatkoweinfo_gatunek_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (2, 'Dom'), (1, 'Samochód'), (3, 'Zdrowotne'), (4, 'Elektronika')], default=0),
        ),
    ]
