# Generated by Django 4.0.2 on 2022-02-13 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ubezpieczenia', '0014_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubezpieczenie',
            name='dodatkowe',
        ),
        migrations.AddField(
            model_name='zamowienia',
            name='uzytkownik',
            field=models.ManyToManyField(related_name='Uzytkownik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='kategoria',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (2, 'Dom'), (4, 'Elektronika'), (1, 'Samochód'), (3, 'Zdrowotne')], default=0),
        ),
        migrations.RemoveField(
            model_name='zamowienia',
            name='ubezpieczenie',
        ),
        migrations.AddField(
            model_name='zamowienia',
            name='ubezpieczenie',
            field=models.ForeignKey(default="1", on_delete=django.db.models.deletion.CASCADE, to='ubezpieczenia.ubezpieczenie'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DodatkoweInfo',
        ),
    ]
