# Generated by Django 4.0.2 on 2022-02-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0015_remove_ubezpieczenie_dodatkowe_zamowienia_uzytkownik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='kategoria',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Samochód'), (2, 'Dom'), (3, 'Zdrowotne'), (4, 'Elektronika'), (0, 'Inne')], default=0),
        ),
    ]
