# Generated by Django 4.0.2 on 2022-02-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubezpieczenia', '0016_alter_ubezpieczenie_kategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubezpieczenie',
            name='kategoria',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Dom'), (1, 'Samochód'), (3, 'Zdrowotne'), (0, 'Inne'), (4, 'Elektronika')], default=0),
        ),
        migrations.RemoveField(
            model_name='zamowienia',
            name='ubezpieczenie',
        ),
        migrations.AddField(
            model_name='zamowienia',
            name='ubezpieczenie',
            field=models.ManyToManyField(related_name='Zamowienia', to='ubezpieczenia.Ubezpieczenie'),
        ),
    ]
